### ISSUE TITLE
PYMC3 support?

### ISSUE THREAD

**Issue by pavolgaj** [pavolgaj/OCFit#8]
_From email communication:_ 

We have attempted to run your OCFit code but we are having difficulty with pymc. Our system is running anaconda/python3.7 on macOS. For this version of anaconda we are only able to install pymc3 and this version is not defined in the code itself. In order to get around that we manually changed all occurrences of pymc with pymc3. However, this still generates the following error...

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/pymc3/model.py", line 299, in get_context
    candidate = cls.get_contexts()[idx]  # type: Optional[T]
IndexError: list index out of range
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 52, in __new__
    model = Model.get_context()
  File "//anaconda3/lib/python3.7/site-packages/pymc3/model.py", line 304, in get_context
    raise TypeError("No %s on context stack" % str(cls))
TypeError: No <class 'pymc3.model.Model'> on context stack
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/edasonbas/Documents/OCFit-master/py3/gui/ocfit-gui.py", line 760, in fitMC
    else: ocf.FitMCMC(mc['n'],mc['burn'],mc['binn'])
  File "//anaconda3/lib/python3.7/site-packages/OCFit/OC_class.py", line 1496, in FitMCMC
    pars[p]=pymc3.Uniform(p,lower=self.limits[p][0],upper=self.limits[p][1],value=self.params[p])
  File "//anaconda3/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 54, in __new__
    raise TypeError("No model on context stack, which is needed to "
TypeError: No model on context stack, which is needed to instantiate distributions. Add variable inside a 'with model:' block, or use the '.dist' syntax for a standalone distribution.  
```

**Comment by pavolgaj** [comment]
OCFit is only compatible with older pymc (version 2)! 
You can try to build old pymc from source (https://github.com/pymc-devs/pymc) or try to install it using pip (https://pypi.org/project/pymc/). There is also some pymc package on anaconda webpage (https://anaconda.org/anaconda/pymc).

I haven't any problem to install pymc in python 3.7 on Linux. 

In a far future, OCFit may be modified to use pymc3 or emcee...

**Comment by pavolgaj** [comment]
Change MC fitting from pymc to emcee. I don't know about any compatibility problems with emcee package in python 2 or 3 on any OS.

Fixed in dev branch (https://github.com/pavolgaj/OCFit/tree/dev) by commit https://github.com/pavolgaj/OCFit/commit/b5e4f7ca027175d8dd209f023af9a9c5b6aff9ad.
